---
title: "Tejon mammal trapping"
author: "sbsambado"
date: "9/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(vegan)
library(devtools)
devtools::install_github('gavinsimpson/ggvegan')

```


Excel sheet called 'tejon_mammals1819_09022020'
```{r dataframes}

# full dataset
mammals <- read.csv("~/Desktop/tejon_mammals1819_09022020.csv")

# subset for important
mammal <-data.frame(mammals[,4:6],mammals[,9])
View(mammal)

# mammal count dataframe
Count <- read.csv("~/Desktop/tejon_mammalcount_09032020.csv", header = TRUE)

count <- Count[-4,]

numeric <- count[,c(-1,-2,-9,-10)]

sppr <- specnumber(numeric)

count$sppr<-specnumber(numeric)



pal <- c("lightsalmon1", "gold1", "palegreen4")

## species richness by site
site_sppr <- ggplot(count, aes(x = site, y = sppr))+
  geom_boxplot(fill = pal) +
  scale_x_discrete(labels = c("Arid", "Intermediate", "Mesic")) +
  theme(legend.position = "none",
        plot.background = element_rect("white"),
        panel.background = element_rect("white"),
        panel.grid = element_line("grey90"),
        axis.line = element_line("gray25"),
        axis.text = element_text(size = 12, color = "gray25"),
        axis.title = element_text(color = "gray25"),
        legend.text = element_text(size = 12)) + 
  labs(x = "Ecological landtype",
       y = "Number of species per site",
       title = "Species richness")+
  theme_classic()
site_sppr


count$plot <- factor(count$plot, 
                        levels = c('open','partial','total'))


## species richness by site
plot_sppr <- ggplot(count, aes(x = plot, y = sppr))+
  geom_boxplot(fill = c('red','blue','green')) +
  scale_x_discrete(labels = c("Open", "Partial", "Total")) +
  theme(legend.position = "none",
        plot.background = element_rect("white"),
        panel.background = element_rect("white"),
        panel.grid = element_line("grey90"),
        axis.line = element_line("gray25"),
        axis.text = element_text(size = 12, color = "gray25"),
        axis.title = element_text(color = "gray25"),
        legend.text = element_text(size = 12)) + 
  labs(x = "Ecological landtype",
       y = "Number of species per plot",
       title = "Species richness")+
  theme_classic()
plot_sppr



# species diversity by plot with error bars

plot_sppr_error <- ggplot(data = count,
       aes(x = plot, y = sppr,
           fill = plot))+
  geom_bar(stat = 'summary', fun.y = 'mean')+
  stat_summary(geom = 'errorbar', fun.data = mean_se, width = .4)+
  scale_fill_manual(values = c('lightblue4','lightblue3','lightblue'))+
  theme_classic()+
  xlab('Plot') + ylab('Spieces Richness')+
  ggtitle('Species Diversity by Plot')+
  theme(plot.title = element_text(face = 'bold', hjust = 0.5)) 
  # #annotate('text', label = 'a', 
  #          x = 1, y = 1.6,
  #          size = 9, color = 'red') +
  # #annotate('text', label = 'b', 
  #          x = 2, y = 3.4,
  #          size = 9, color = 'red') +
  #   #annotate('text', label = 'b', 
  #          x = 3, y = 4.3,
  #          size = 9, color = 'red')
  # 


# total animal abundance by plot
plot1<-ggplot(data = count,
       aes(x = plot, y = total,
           fill = plot))+
  geom_bar(stat = 'summary', fun.y = 'mean')+
  stat_summary(geom = 'errorbar', fun.data = mean_se, width = .4)+
  scale_fill_manual(values = c('lightblue4','lightblue3','lightblue'))+
  theme_classic()+
  xlab('Plot') + ylab('Total Animal Abundance')+
  ggtitle('Total Animal Abundance by Plot')+
  theme(plot.title = element_text(face = 'bold', hjust = 0.5)) 


## # total animal abundance by site with fill
site1<-ggplot(data = count,
       aes(x = site, y = total,
           fill = plot))+
  geom_bar(stat = 'summary', fun.y = 'mean')+
  stat_summary(geom = 'errorbar', fun.data = mean_se, width = .4)+
  scale_fill_manual(values = c('lightblue4','lightblue3','lightblue'))+
  theme_classic()+
  xlab('Site') + ylab('Total Animal Abundance')+
  ggtitle('Total Animal Abundance by Site')+
  theme(plot.title = element_text(face = 'bold', hjust = 0.5)) 


## # total animal abundance by site no fill
site2<-ggplot(data = count,
       aes(x = site, y = total))+
  geom_bar(stat = 'summary', fun.y = 'mean',
           fill = c('lightblue4','lightblue3','lightblue'))+
  stat_summary(geom = 'errorbar', fun.data = mean_se, width = .4)+
  theme_classic()+
  xlab('Site') + ylab('Total Animal abundance')+
  ggtitle('Total Animal abundance by Site')+
  theme(plot.title = element_text(face = 'bold', hjust = 0.5)) 

ggarrange(site_sppr, plot_sppr, plot_sppr_error, plot1,
          site1, site2)

```


```{r shannondiv}

shannondiv <- diversity(numeric)

## # shannon by site with fill
site3<-ggplot(data = count,
       aes(x = site, y = shannondiv,
           fill = plot))+
  geom_bar(stat = 'summary', fun.y = 'mean')+
  stat_summary(geom = 'errorbar', fun.data = mean_se, width = .4)+
  scale_fill_manual(values = c('lightblue4','lightblue3','lightblue'))+
  theme_classic()+
  xlab('Site') + ylab('Shannon Diversity')+
  ggtitle('Shannon Diversity by Site')+
  theme(plot.title = element_text(face = 'bold', hjust = 0.5)) 


## # shannon by site no fill
site4<-ggplot(data = count,
       aes(x = site, y = shannondiv))+
  geom_bar(stat = 'summary', fun.y = 'mean',
           fill = c('lightblue4','lightblue3','lightblue'))+
  stat_summary(geom = 'errorbar', fun.data = mean_se, width = .4)+
  theme_classic()+
  xlab('Site') + ylab('Shannon Diversity')+
  ggtitle('Shannon Diversity by Site')+
  theme(plot.title = element_text(face = 'bold', hjust = 0.5)) 
site3
site4

ggarrange(site_sppr, plot_sppr, plot_sppr_error, plot1,
          site1, site2)

```


```{r}
newcount <- count[c(-1)]

# row, column
Arid <- count[c(1:3),c(-1,-2,-9,-10)]
library(data.table)
setDT(Arid, keep.rownames = TRUE)[]

Aridd <- Arid[,-1]

site_type <-count%>%
  select(site, plot) 


sppr <- specnumber(Aridd)

sppr_aov <- aov(sppr~site, data = site_type )

library(dplyr)
countnumeric <-count %>% mutate_if(is.integer, as.numeric)
count <- countnumeric
#View(count)
head(count)
str(count)

row.names(count, make.names = TRUE)

ord <-metaMDS(count)
```



```{r ANOVA}

p<-aov(sppr~ plot, data = count)
summary(p)

s<-aov(sppr~ site, data = count)
summary(s)

count$shannondiv <- diversity(numeric)
sppdiv_site_aov <- aov(shannondiv ~ site, data = count)
summary(sppdiv_site_aov) ## p = 0.0483 for site

sppdiv_plot_aov <- aov(shannondiv ~ plot, data = count)
summary(sppdiv_plot_aov) 

tot_plot_aov <- aov(total ~ plot, data = count)
summary(tot_plot_aov)

tot_site_aov <- aov(total ~ site, data = count)
summary(tot_site_aov) # p = 0.00857 for site 



```

```{r vegan by An Bui PCA}

# https://rpubs.com/an-bui/vegan-cheat-sheet

mammalPCA <- rda(numeric)
mammalPCA
#An's
PCAscores <- scores(mammalPCA, display = "sites") %>% 
  as.data.frame() %>% 
  rownames_to_column("site") %>% 
  full_join(site_type, by = "site")


PCAvect <- scores(mammalPCA, display = "species") %>% 
  as.data.frame()

plot_PCA <- ggplot() +
  geom_point(data = PCAscores, aes(x = PC1, y = PC2, color = site)) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  geom_segment(data = PCAvect, aes(x = 0, y = 0, xend = PC1, yend = PC2), arrow = arrow(length = unit(0.2, "cm"))) +
  geom_text(data = PCAvect, aes(x = PC1, y = PC2, label = rownames(PCAvect))) +
  labs(x = "PC1 (23.57%)",
       y = "PC2 (12.23%)",
       title = "Principal Components Analysis") 
plot_PCA

library(ggvegan)
PCA_biplot <- autoplot(mammalPCA)

# fortify()
PCA_fortify <- fortify(mammalPCA)

# extract site coords (points)
PCA_fort_sites <- PCA_fortify %>% 
  filter(Score == "sites") %>% 
  full_join(., site_type, by = c("Label" = "site"))

# extract species coords (segment)
PCA_fort_species <- PCA_fortify %>% 
  filter(Score == "species")

PCA_fortify_plot <- ggplot() +
  geom_point(data = PCA_fort_sites, aes(x = PC1, y = PC2)) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  scale_color_manual(values = c("coral", "lightgreen", "darkblue")) +
  geom_segment(data = PCA_fort_species, aes(x = 0, xend = PC1, y = 0, yend = PC2), 
               arrow = arrow(length = unit(0.2, "cm"))) +
  geom_text(data = PCA_fort_species, aes(x = PC1, y = PC2, label = Label)) +
  labs(x = "PC1 (23.57%)",
       y = "PC2 (12.23%)",
       title = "Principal Components Analysis - using fortify()")
PCA_fortify_plot

## Option Non-metric Multidimensional Scaling (NMDS)
mammal_NMDS <- metaMDS(numeric)
plot_df <- scores(mammal_NMDS, display = "sites") %>% 
  as.data.frame() %>% 
  rownames_to_column("site") %>% 
  full_join(site_type, by = "site")

plot_nmds <- ggplot(plot_df, aes(x = NMDS1, y = NMDS2, color = site, shape = site)) +
  geom_point(size = 3, alpha = 0.8) +
  stat_ellipse(linetype = 2, size = 1) +
  labs(title = "NMDS")
plot_nmds


### Option Canonical Correspondence Analysis
mammalCCA <- cca(numeric ~ plot + site, data = count)
mammalCCA

ccaplot <- plot(mammalCCA)

ccavectors <- as.matrix(scores(mammalCCA, display = "bp", scaling = "species")*12.2) %>% 
  as.data.frame()

site_data <- scores(mammalCCA, display = "sites") %>% 
  as.data.frame() %>% 
  rownames_to_column("site") %>% 
  full_join(site_type, by = "site")

species_data <- scores(mammalCCA, display = "species") %>% 
  as.data.frame()

plot_cca <- ggplot(site_data) +
  geom_point(aes(x = CCA1, y = CCA2), shape = 19, size = 2, alpha = 0.8) +
  coord_fixed() +
  scale_color_manual(values = pal) +
  geom_segment(data = ccavectors, aes(x = 0, y = 0, xend = CCA1, yend = CCA2), arrow = arrow(length = unit(0.2, "cm"))) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  geom_point(data = species_data, aes(x = CCA1, y = CCA2), shape = 17, size = 2, color = "slateblue") +
  scale_x_continuous(limits = c(-12, 10)) +
  scale_y_continuous(limits = c(-3, 12)) +
  geom_text(data = ccavectors, aes(x = CCA1, y = CCA2, label = rownames(ccavectors)), nudge_x = 0.3, nudge_y = 0.3) +
  labs(title = "Canonical Correspondence Analysis")
plot_cca


```

```{r PCA by Tatum}
library(grid)
library(gridExtra)

mam.pca <- prcomp(numeric, center = TRUE, scale = TRUE)
print(mam.pca)
plot(mam.pca, type = 'l')
summary(mam.pca)

out <- as.data.frame(mam.pca$x) #get the PC values for each observation so we can plot it

out$site <-c('arid','arid','arid',
                 'intermediate','intermediate','intermediate',
                 'mesic','mesic','mesic')
ggplot(out, aes(x=PC1, y=PC2, color = site))+
  clean_background+
  geom_point()


clean_background <- theme(plot.background = element_rect("white"),
        panel.background = element_rect("white"),
        panel.grid = element_line("white"),
        axis.line = element_line("gray25"),
        axis.text = element_text(size = 12, color = "gray25"),
        axis.title = element_text(color = "gray25"),
        legend.text = element_text(size = 12),
        legend.key = element_rect("white"))

## try 2

numeric <- count[,c(-1,-2,-9,-10)]

install.packages('ggfortify')
library(ggfortify)
pca_res <-prcomp(numeric, scale. = TRUE)
autoplot(pca_res, data = out, color = 'site')


```


```{r EDA 1st attempt failed}



count(mammal$site == 'Arid') # 92
count(mammal$site == 'Mesic') #182
count(mammal$site == 'Interm') #43

count(mammal$plot == 'Open') # 69
count(mammal$plot == 'Partial') #116
count(mammal$plot == 'Total') #129

install.packages('vegan')
library(vegan)

sppr <- specnumber(mammal)

sppr_aov1 <- aov(sppr ~ plot, data = mammal)
summary(sppr_aov1)

sppr_aov2 <- aov(sppr ~ site, data = mammal)
summary(sppr_aov2)

## need to fix this
sppr_df <- sppr %>%
  enframe()

plot_sppr <-ggplot(sppr_df, aes(x = mammal$site, y = sppr))+
  geom_boxplot()

shannondiv <- diversity(sppr)



ggplot(data = count,
       aes(x = site, y = total))+
  geom_bar(stat = 'summary', fun.y = 'mean')+
  stat_summary(geom = 'errorbar', fun.data = mean_se, width = .4)+
  scale_fill_manual(values = c('lightblue4','lightblue3','lightblue'))+
  theme_classic()+
  xlab('Plot') + ylab('Total Ticks')+
  ggtitle('Total Ticks by Plot')+
  theme(plot.title = element_text(face = 'bold', hjust = 0.5)) 


## cluster analysis
library(dendextend)
library(factoextra)

m <- dist(as.matrix(count))
hc <- hclust(m)
plot(hc)

fviz_nbclust(count, FUN = hcut, method = 'silhouette')

dend <- as.dendrogram(hc)
dend <-color_branches(dend, k = 3)
dend <- set(dend, 'labels_cex', 0.5)
plot(dend)

```


```{r post hoc site is significant for tot abundance }

sppr_plot<-aov(sppr~ plot, data = count) # not significant

sppr_site<-aov(sppr~ site, data = count) # not significant

sppd_site <- aov(shannondiv ~ site, data = count) # not significant

sppd_plot<- aov(shannondiv ~ plot, data = count) # not significant

tot_plot<- aov(total ~ plot, data = count) # not significant

tot_site <- aov(total ~ site, data = count) # significant for mesic b, arid & interm a


# Tukey-Kramer test assumes that I've already ran an ANOVA & rejected my H0 (all means are equal across groups)
TukeyHSD(tot_site)

# let's do this in a visual way
Post_hoctot_site <-glht(tot_site, linfct = mcp(site = 'Tukey'))
summary(Post_hoctot_site)

confint(Post_hoctot_site) # pairwise test
cld(Post_hoctot_site) # different letters are different from each other open is different than partial & total!
plot(Post_hoctot_site) # plot 95% CIs

```


possibly tick abundance with mammal abundance correlation?
```{r correlation}

cor.test(combo$total_ticks, combo$total_mammal)
cor.test(combo$shan_mammal, combo$total_mammal) # significant but colinear?
cor.test(combo$rich_mammal, combo$total_mammal) # significant but colinear?
cor.test(combo$total_ticks, combo$shan_mammal) # significant

```


```{r vegan example}
birds <- read_csv(here::here('data', 'bird-comm.csv')) %>%
  column_to_rownames('site')

env <- read_csv(here::here('data', 'env-var.csv'))

site_type <- env %>%
  select(site, landtype)
```

